### PR TITLE
Add $ref support for ComboBox + some optimization

### PR DESCRIPTION
**Pull request by almirus**
code deduplication and add $ref support for ComboBox

### CODE REVIEW

**Review by SaifJerbi — APPROVED** [review]
Good work to improve the code quality and remove code duplication

**Comment by SaifJerbi** [comment]
Hi @almirus,
Thanks for your contribution,
Could you please update the [documentation](https://github.com/JsonSchema-JavaUI/sf-java-ui/blob/master/docs/index.md) and describe the new added property ?

**Comment by almirus** [comment]
I do not speak English well.
Examples for $ref:
https://github.com/json-schema-form/angular-schema-form/blob/bd182950b78c68ac3556b399fbaf3e3ea9a33232/examples/data/jsonref.json
https://github.com/json-schema-form/json-schema-form-core/issues/1

It may be necessary to add support $ref for all fields

**Comment by SaifJerbi** [comment]
I found the combo box and the check box documentation aren't published yet, so i will add this property in the doc and publish that ASAP.
Don't hesitate if you find any improvement to do

**Pull request merged**
